# Generated by Django 5.1.5 on 2025-10-11 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("capacity", models.IntegerField()),
                ("booked_count", models.IntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="booking_system.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "indexes": [
                    models.Index(
                        fields=["activity", "start_time"],
                        name="booking_sys_activit_dcc9e1_idx",
                    ),
                    models.Index(
                        fields=["start_time", "is_available"],
                        name="booking_sys_start_t_d75ed8_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("booked_count__lte", models.F("capacity"))),
                        name="booked_count_within_capacity",
                    ),
                    models.UniqueConstraint(
                        fields=("activity", "start_time"),
                        name="unique_activity_timeslot",
                    ),
                ],
            },
        ),
    ]
