# Generated by Django 5.1.5 on 2025-10-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0003_userpreference_booking"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE booking_system_activity DROP COLUMN IF EXISTS image_url;",
            reverse_sql="ALTER TABLE booking_system_activity ADD COLUMN image_url VARCHAR(500) NOT NULL DEFAULT '';",
        ),
    ]
