# Generated by Django 5.1.5 on 2025-10-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="user_phone",
            field=models.CharField(
                db_index=True,
                help_text="User's phone number in WhatsApp format (e.g., whatsapp:+14155238886)",
                max_length=50,
            ),
        ),
    ]
