services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=whatsapp_chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile.backend
    command: gunicorn backend.whatsapp_ai_chatbot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../backend:/app/backend
      - ../logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile.backend
    command: celery -A backend.whatsapp_ai_chatbot worker --loglevel=info
    volumes:
      - ../backend:/app/backend
      - ../logs:/app/logs
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile.backend
    command: celery -A backend.whatsapp_ai_chatbot beat --loglevel=info
    volumes:
      - ../backend:/app/backend
      - ../logs:/app/logs
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
