# Generated by Django 5.1.5 on 2025-10-11 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("watersports", "Watersports"),
                            ("spa", "Spa"),
                            ("dining", "Dining"),
                            ("adventure", "Adventure"),
                            ("wellness", "Wellness"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("duration_minutes", models.IntegerField()),
                ("capacity_per_slot", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
                ("requirements", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="booking_sys_categor_278479_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="booking_sys_is_acti_dd35b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="activities/")),
                ("alt_text", models.CharField(max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="booking_system.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Image",
                "verbose_name_plural": "Activity Images",
                "ordering": ["order", "id"],
            },
        ),
    ]
