# Generated by Django 5.1.5 on 2025-10-11 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0002_timeslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("preferred_categories", models.JSONField(default=list)),
                ("preferred_times", models.JSONField(default=list)),
                ("budget_range", models.JSONField(default=dict)),
                ("interests", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_phone", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("participants", models.IntegerField(default=1)),
                ("special_requests", models.TextField(blank=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "booking_source",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("web", "Web")],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking_system.activity",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking_system.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "indexes": [
                    models.Index(
                        fields=["user_phone", "-created_at"],
                        name="booking_sys_user_ph_bed4d6_idx",
                    ),
                    models.Index(
                        fields=["status", "time_slot"],
                        name="booking_sys_status_b8fbb6_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "status"],
                        name="booking_sys_expires_f49cb7_idx",
                    ),
                ],
            },
        ),
    ]
